server:
  port: 8100
resilience4j:
  #retry:
    #instance:
      #foo-bar:
        #maxAttempts: 7
        #waitDuration: 1s
        #simular ao fibonacci - aumenta o tempo de espera para fazer requisição
        #enableExponentialBackoff: true
  #rateLimiter:
    #instances:
      #default:
        #limiteForPeriod: 2
        #limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
      foo-bar:
        maxConcurrentCalls: 10

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password:
    jpa:
      hibernate:
        #makes no change to the schema
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    '[org.apache.zookeeper.ClientCnxn]': WARN
